INSERT INTO questions (question_text, option_a, option_b, option_c, option_d, correct_option) VALUES
('What is Java?', 'A platform', 'A language', 'Both platform and language', 'None of the above', 'C'),
('Which keyword declares a constant?', 'const', 'final', 'static', 'immutable', 'B'),
('Which of these is not in java.util package?', 'List', 'Map', 'Tree', 'Scanner', 'C'),
('Size of int in Java?', '16 bits', '32 bits', '64 bits', 'Depends on architecture', 'B'),
('Which method starts a thread?', 'run()', 'start()', 'init()', 'main()', 'B'),
('Exception on division by zero?', 'NullPointerException', 'IOException', 'ArithmeticException', 'ClassNotFoundException', 'C'),
('Keyword for inheritance?', 'extends', 'implements', 'inherits', 'derives', 'A'),
('Default boolean value?', 'true', 'false', 'null', '0', 'B'),
('Which package has List?', 'java.util', 'java.lang', 'java.io', 'java.net', 'A'),
('Interface for iteration?', 'Iterable', 'Iterator', 'Comparable', 'Serializable', 'A'),
('Which is unchecked exception?', 'IOException', 'SQLException', 'ArithmeticException', 'ClassNotFoundException', 'C'),
('super() refers to?', 'Current class', 'Parent class constructor', 'Static method', 'Interface default', 'B'),
('Method overloading is?', 'Same name different params', 'Same signature in subclass', 'Different return types only', 'All true', 'A'),
('What is wrapper for int?', 'Integer', 'Int', 'iWrapper', 'Num', 'A'),
('String is immutable?', 'True', 'False', 'Only in Java 9+', 'Depends on implementation', 'A'),
('Select valid enum declaration', 'enum Color {RED}', 'Color enum {RED}', 'enum {RED}', 'enum;Color;', 'A'),
('Finally block executes when?', 'After try', 'After catch', 'Even if return in try', 'Only on exceptions', 'C'),
('Generics introduced in Java version?', 'Java 4', 'Java 5', 'Java 6', 'Java 7', 'B'),
('Which keyword prevents inheritance?', 'stop', 'final', 'private', 'static', 'B'),
('Collection without duplicates?', 'List', 'Set', 'Queue', 'Map', 'B'),
('Interface methods are by default?', 'public', 'private', 'protected', 'package-private', 'A'),
('Lambda introduced in?', 'Java 7', 'Java 8', 'Java 9', 'Java 6', 'B'),
('Use synchronized keyword for?', 'Serialization', 'Concurrency control', 'Testing', 'Parsing', 'B'),
('Serializable interface is?', 'Marker', 'Functional', 'Abstract', 'Generic', 'A'),
('Thread.sleep() throws?', 'InterruptedException', 'RuntimeException', 'Error', 'IOException', 'A'),
('Which is immutable collection?', 'ArrayList', 'HashSet', 'Collections.unmodifiableList()', 'LinkedList', 'C'),
('Default value for object reference?', '0', 'undefined', 'null', 'None', 'C'),
('Enhances for loop syntax:', 'for(int i: arr)', 'foreach(int i in arr)', 'loop(int i; arr)', 'iterate(int i: arr)', 'A'),
('StringBuilder vs StringBuffer?', 'Buffer is faster', 'Builder is synchronized', 'Builder is synchronized', 'Both same', 'B'),
('Which method to get length of array?', 'size()', 'length()', 'getLength()', 'count()', 'B'),
('== on objects compares?', 'Value', 'Reference', 'hashcode', 'content equality', 'B'),
('HashMap permits null key?', 'Yes', 'No', 'Only in Java 8+', 'Only in values', 'A'),
('volatile keyword ensures?', 'Visibility guarantee', 'Atomicity', 'Security', 'None', 'A'),
('abstract class instantiation?', 'Allowed', 'Not allowed', 'Allowed via new', 'Allowed if no methods', 'B'),
('Default access modifier is?', 'public', 'private', 'protected', 'package-private', 'D'),
('Static import introduced in Java?', 'Java 4', 'Java 5', 'Java 6', 'Java 7', 'B'),
('Checked exceptions must be?', 'Handled or declared', 'Ignored', 'Only runtime', 'Auto-handled', 'A'),
('String method to compare content?', '==', 'compare()', 'equals()', 'match()', 'C'),
('Which class loads classes?', 'ClassLoader', 'Class', 'Loader', 'Compiler', 'A'),
('Convert string to int?', 'Integer.parseInt()', 'String.toInt()', 'parse.Int()', 'Int.parse()', 'A'),
('Which is thread-safe?', 'Vector', 'ArrayList', 'HashMap', 'LinkedList', 'A'),
('Inner class can be?', 'static', 'non-static', 'anonymous', 'All of the above', 'D'),
('interface vs abstract class?', 'No methods in interface', 'Interface can have default', 'Abstract cannot', 'None', 'B'),
('What is JRE?', 'Java Ready Environment', 'Java Runtime Environment', 'Java Runtime Extension', 'None', 'B'),
('What is JDK?', 'Java Development Kit', 'Java Deployment Kit', 'Java Design Kit', 'None', 'A'),
('Generics support?', 'Type erasure', 'Reification', 'Recompilation', 'None', 'A'),
('Stream API from Java?', 'Java 7', 'Java 8', 'Java 9', 'Java 6', 'B'),
('Optional added in Java?', '7', '8', '9', '10', 'B'),
('What is a functional interface?', 'Interface with static method', 'Interface with one abstract method', 'Any interface', 'Interface with default method', 'B'),
('Default method in interface needs?', 'abstract', 'default keyword', 'public', 'static', 'B'),
('Boxing means?', 'Primitive to wrapper', 'Wrapper to primitive', 'Copying objects', 'Cloning', 'A'),
('Enum extends?', 'Enum', 'java.lang.Enum', 'Object', 'None', 'B'),
('Which is final method?', 'Cannot override', 'Cannot overload', 'Both', 'None', 'A'),
('Which is good for key-value pairs?', 'List', 'Set', 'Map', 'Queue', 'C'),
('Thread priorities range?', '1–5', '1–10', '0–10', '0–5', 'B'),
('join() on thread does?', 'Remove thread', 'Pause main until thread dies', 'Terminate thread', 'None', 'B'),
('RuntimeException is checked?', 'Yes', 'No', 'Only in Java 7', 'Depends', 'B'),
('Scanner uses what package?', 'java.io', 'java.util', 'java.lang', 'java.net', 'B'),
('StringBuffer is?', 'Immutable', 'Mutable', 'Final', 'Static', 'B'),
('FileReader located in?', 'java.io', 'java.nio', 'java.util', 'java.lang', 'A'),
('Which method of Thread class?', 'wait()', 'sleep()', 'yield()', 'All of above', 'D'),
('Method overriding needs same?', 'Name only', 'Signature only', 'Signature return type and exceptions', 'None', 'C'),
('Which collection is sorted?', 'HashMap', 'HashSet', 'TreeSet', 'LinkedHashSet', 'C'),
('Which interface represents a double-ended queue?', 'List', 'Deque', 'Queue', 'Map', 'B'),
('Which exception indicates class not found?', 'InstantiationException', 'IllegalAccessException', 'ClassNotFoundException', 'NoClassDefFoundError', 'C'),
('Thread group manages?', 'Collection', 'Threads', 'Singletons', 'Exceptions', 'B'),
('System.out is?', 'OutputStream', 'PrintStream', 'DataOutputStream', 'Writer', 'B'),
('volatile variable updated?', 'Immediately visible to all threads', 'Cached only', 'Atomic update', 'Lazy update', 'A'),
('Which is marker interface?', 'Cloneable', 'List', 'Runnable', 'Serializable', 'D'),
('Which is mutable class?', 'String', 'StringBuilder', 'Integer', 'Double', 'B'),
('static methods can access?', 'Instance variables', 'Static variables', 'Both', 'None', 'B'),
('main method must be?', 'public static void main(String[] args)', 'private static void', 'public void main()', 'public static int main()', 'A'),
('Which operator is null-safe?', '?.', '?:', '!?.', 'No operator', 'D'),
('What is diamond operator <>', 'Type inference in generics', 'Less memory', 'Better performance', 'Deprecated syntax', 'A'),
('Iterator removal safe?', 'List)', 'Map', 'Set', 'Collection', 'C'),
('Which class used for date in Java 8?', 'Date', 'Calendar', 'LocalDate', 'SimpleDateFormat', 'C'),
('Which method formats date?', 'format()', 'parse()', 'of()', 'create()', 'A'),
('Try-with-resources introduced in?', 'Java 6', 'Java 7', 'Java 8', 'Java 9', 'B'),
('Suppress warnings annotation?', '@SafeVarargs', '@SuppressWarnings', '@Override', '@Deprecated', 'B'),
('Which reflects class at runtime?', 'Reflection', 'Annotation', 'Serialization', 'Collection', 'A'),
('Which method sorts list?', 'Collections.sort()', 'List.sort()', 'sort()', 'order()', 'A'),
('Which converts list to stream?', 'list.stream()', 'list.toStream()', 'stream(list)', 'list.asStream()', 'A'),
('Which exception is thrown by new?', 'NullPointerException', 'OutOfMemoryError', 'InstantiationException', 'IOException', 'B'),
('Which cannot be serialized?', 'StringBuffer', 'ArrayList', 'Transient variables', 'Serializable objects', 'C'),
('Assert keyword enabled by?', '-ea flag', '-enable', '-assert', 'None', 'A'),
('Which collects garbage?', 'JVM', 'JIT', 'GC', 'JIT compiler', 'C'),
('Which is JIT?', 'Just-In-Time compiler', 'Java Input Tool', 'Java Integration Tool', 'Joint Interface Tool', 'A'),
('Compile-time polymorphism is?', 'Method overriding', 'Method overloading', 'Interface implementation', 'Class instantiation', 'B'),
('Runtime polymorphism is?', 'Overloading', 'Overriding', 'Abstract class', 'Final method', 'B'),
('Which is immutable list in Java 9?', 'Arrays.asList()', 'List.of()', 'Collections.singleton()', 'None', 'B'),
('Which method on Optional?', 'get()', 'orElse()', 'map()', 'All', 'D'),
('Which annotation denotes test method?', '@Test', '@Run', '@Check', '@Validate', 'A'),
('Stream filter returns?', 'Map', 'List', 'Stream', 'Set', 'C'),
('Which can be local class?', 'Static', 'Non-static', 'Both', 'Neither', 'C'),
('Sublist from List method?', 'subList()', 'slice()', 'segment()', 'part()', 'A'),
('Which keyword for exception chaining?', 'throw', 'throws', 'Throwable', 'chained', 'A'),
('Default value for int?', '0', 'null', 'undefined', '-1', 'A'),
('Which path separator on Windows?', ';', ':', ',', '|', 'A'),
('Which JVM argument shows memory usage?', '-Xmx', '-Xms', '-verbose:gc', '-showMem', 'C');

